# Financial Planning Configuration

# Database settings
database:
  type: sqlite
  path: ./data/app.db
  echo: false  # Set to true for SQL query logging

# API settings
api:
  host: 0.0.0.0
  port: 8000
  reload: true
  cors_origins:
    - "http://localhost:3000"
    - "http://localhost:5173"

# Logging configuration
logging:
  level: INFO
  format: json  # json or text
  file: ./data/logs/app.log

# Application settings
app:
  base_currency: USD
  timezone: UTC
  data_adapters:
    enabled: false  # Disable by default for local-first operation
    price_adapter: null
    fx_adapter: null

# Security settings
security:
  db_encryption: false
  backup_encryption: false
  max_backup_files: 10

# Performance settings
performance:
  cache_prices: true
  cache_ttl: 3600  # seconds
  max_db_connections: 10
