# Financial Planning Application Configuration

# Database settings
database:
  path: "./data/app.db"  # SQLite database file path
  echo: false            # Set to true for SQL query debugging
  
# API settings  
api:
  host: "localhost"
  port: 8000
  debug: true           # Set to false in production
  reload: true          # Set to false in production
  
# Logging configuration
logging:
  level: "INFO"         # DEBUG, INFO, WARNING, ERROR, CRITICAL
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "./data/app.log" # Log file path, null for stdout only
  max_file_size: "10MB" # Maximum log file size before rotation
  backup_count: 5       # Number of backup log files to keep

# Adapter settings (disabled by default for local-first principle)
adapters:
  price_adapter:
    enabled: false      # Enable external price data fetching
    provider: null      # e.g., "yahoo", "alpha_vantage", etc.
    api_key: null       # API key for external provider
    cache_ttl: 3600     # Cache time-to-live in seconds
    
  fx_adapter:
    enabled: false      # Enable external FX rate fetching  
    provider: null      # e.g., "ecb", "fixer", etc.
    api_key: null       # API key for external provider
    cache_ttl: 3600     # Cache time-to-live in seconds
    
  broker_import:
    enabled: false      # Enable broker-specific import adapters
    providers: []       # List of enabled broker adapters

# Application settings
app:
  timezone: "UTC"       # Default timezone for data processing
  base_currency: "USD"  # Default base currency for multi-currency operations
  backup_on_startup: true  # Create database backup on application startup
  backup_retention_days: 30  # Number of days to keep backup files